### ISSUE TITLE
Assertion Error when running utils.loocv_backward function with multiple cpus

### ISSUE THREAD

**Issue by SKMuller** [GWeindel/hsmm_mvpy#123]
When performing the utils.loocv_backward function with more than 1 cpu, the function returns an Assertion Error after some time during the process. Running the function without assigning extra cpus runs just fine.

**Comment by GWeindel** [comment]
@jelmerborst can we mark this as fixed with #124 ?

**Comment by jelmerborst** [comment]
Yep, fixed with #124.
