### ISSUE TITLE
Random generation of starting points yields RuntimeWarning because of starting points larger than the mean RT

### ISSUE THREAD

**Issue by GWeindel** [GWeindel/hsmm_mvpy#38]
Title explicit. For now, it is dealt with ignoring the warning as the error is not too bad. This however probably points to the fact that random generation of starting points is yet inefficient.

Ways to reproduce 
```python
init = hmp.models.hmp(hmp_data, sfreq=eeg_data.sfreq, bump_width=50, cpus=cpus)#Initialization of the model
selected = init.fit_single(number_of_sources-1, method='random', starting_points=10)#function to fit an instance of a 4 bumps model
```

**Comment by GWeindel** [comment]
```python
                    proposal_p[1:-1,1] -= self.location
```
Fixes that error but generated parameters can then be negative. Future correction needs to integrate this constrain in the generation of random starting points

**Comment by GWeindel** [comment]
Issue is actually still present. For now the error message is hidden:
```filterwarnings("ignore", category=RuntimeWarning)#Error in the generation of random see GH issue #38```

**Comment by jelmerborst** [comment]
fixed by https://github.com/GWeindel/hsmm_mvpy/pull/60/commits/80210a72dceb8159b92ea91b7d7b57f498602316

**Comment by jelmerborst** [comment]
apparently it is back, at least when calling the fit function:
![Screenshot 2023-06-27 at 17 02 24](https://github.com/GWeindel/hsmm_mvpy/assets/19282335/cd158a08-0a07-4f95-b682-1e9acde3cbdc)

**Comment by jelmerborst** [comment]
fixed previously by:
`eventprobs[eventprobs < 0] = 0 #floating point precision error`
Not sure how this can happen anymore.

**Comment by GWeindel** [comment]
This is very likely specific to the starting point generation of the fit function, I am currently on it

**Comment by GWeindel** [comment]
Isn't an issue anymore since PR #71
