### ISSUE TITLE
Durations and mean_d are based on max durations per subject instead of mean

### ISSUE THREAD

**Issue by jelmerborst** [GWeindel/hsmm_mvpy#56]
At least when fitting multiple subjects, `mean_d` and `durations` of the hmp model are based on the max duration (ie number of samples in the matrix) of each subject. They should be based on the mean of each subject.

This might be caused by that `data.unstack()` on line 60 of `models.py` gives the same number of epochs as there are subjects.

**Comment by GWeindel** [comment]
I do not see the problem you're pointing at as the code seems to do what is expected. Can you specify more what the actual vs. the expected behavior of those variables is?

**Comment by jelmerborst** [comment]
If I use hmp_data_format in combination with xr.concat to create a hmp format dataset (as in section 3 of tutorial 1), I get an xarray.Dataset of the following shape: `(epochs: 226, channels: 25, samples: 1082, participant: 3)`.

From this, I create `hmp_data` with `transform_data`:
`hmp_data = hmp.utils.transform_data(epoch_data, apply_standard=True,  apply_zscore=True, method='pca', n_comp=10)`
which is `(component: 10, all_samples: 2250)`, which I assume are all samples concatenated, while removing all NaNs in `hmp_data`, correct?

Next, I initialized an HMP model:
`hmp_model = hmp.models.hmp(hmp_data, epoch_data, cpus=cpus)`

hmp_model.mean_d = 750
hmp_model.durations = [ 637, 531, 1082]

**Comment by jelmerborst** [comment]
Nm, turned out there's an issue with using mne.filter.resample on matrices containing NaNs. After solving that, this bug turned out to be non-existent.
