### ISSUE TITLE
First epoch of participant 4 is empty of sample_data set. Causes kernel crash in tutorial 3 when zscoring by participant.

### ISSUE THREAD

**Issue by jelmerborst** [GWeindel/hsmm_mvpy#68]
When zscoring by participant the kernel crashes in Tutorial 3 when calling hmp.utils.transform(). This is due to (at least) the first epoch of participant 4 not containing any data:

![Screenshot 2023-06-30 at 09 44 57](https://github.com/GWeindel/hsmm_mvpy/assets/19282335/b1378413-f117-4c0d-a7ec-9fe2cb14d648)

Fixed in tutorial 3 by zscoring by trial, but should probably be fixed overall in this dataset – this shouldn't be the case.

**Comment by GWeindel** [comment]
Fixed by #97
