### ISSUE TITLE
Add standard errors to stage duration plots

### ISSUE THREAD

**Issue by jelmerborst** [GWeindel/hsmm_mvpy#76]
Currently the plots of stage duration either show CIs or standard deviation. Would be nice to add SEs.

**Comment by GWeindel** [comment]
This issue should be closed with PR #75 right?

**Comment by jelmerborst** [comment]
No, it now has CIs and standard deviation, but I would also like standard errors. However, for that I need some xarray magic that I don't possess

**Comment by jelmerborst** [comment]
Fixed by PR #96
